//
// Copyright 2020 Roman Skabin
//

#pragma once

#include "core/core.h"

#ifndef GUID_DEFINED
#define GUID_DEFINED
typedef struct // *ID
{
    u32 Data1;
    u16 Data2;
    u16 Data3;
    u8  Data4[8];
} IID, GUID, CLSID;
#endif

#define DECLARE_ID(Type, name) CEXTERN const Type __declspec(selectany) name

#define DECLARE_IID(name)   DECLARE_ID(IID, IID_ ## name)
#define DECLARE_GUID(name)  DECLARE_ID(GUID, GUID_ ## name)
#define DECLARE_CLSID(name) DECLARE_ID(CLSID, CLSID_ ## name)

//
// Common
//

#undef GUID_NULL

//
// KS data format subtypes
//

#undef KSDATAFORMAT_SUBTYPE_WAVEFORMATEX
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_WAVEFORMATEX);

#undef KSDATAFORMAT_SUBTYPE_ANALOG
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_ANALOG);

#undef KSDATAFORMAT_SUBTYPE_PCM
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_PCM);

#undef KSDATAFORMAT_SUBTYPE_IEEE_FLOAT
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_IEEE_FLOAT);

#undef KSDATAFORMAT_SUBTYPE_AC3_AUDIO
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_AC3_AUDIO);

#undef KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL);

#undef KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL_PLUS
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL_PLUS);

#undef KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL_PLUS_ATMOS
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_IEC61937_DOLBY_DIGITAL_PLUS_ATMOS);

#undef KSDATAFORMAT_SUBTYPE_IEC61937_MPEG3
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_IEC61937_MPEG3);

#undef KSDATAFORMAT_SUBTYPE_IEC61937_AAC
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_IEC61937_AAC);

// MP3
#undef KSDATAFORMAT_SUBTYPE_MPEGLAYER3
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_MPEGLAYER3);

// AAC
#undef KSDATAFORMAT_SUBTYPE_MPEG_HEAAC
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_MPEG_HEAAC);

// WMA STD
#undef KSDATAFORMAT_SUBTYPE_WMAUDIO2
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_WMAUDIO2);

// WMA PROC
#undef KSDATAFORMAT_SUBTYPE_WMAUDIO3
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_WMAUDIO3);

// WMA LOSSLESS
#undef KSDATAFORMAT_SUBTYPE_WMAUDIO_LOSSLESS
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_WMAUDIO_LOSSLESS);

// WAV
DECLARE_GUID(KSDATAFORMAT_SUBTYPE_WAVPACK_AUDIO);
